drop database lab;
create database lab;
use lab;
create table PATIENT
    (PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
     FIRST_NAME VARCHAR(50) NOT NULL,
     LAST_NAME VARCHAR(50) NOT NULL,
     AGE INT,
     GENDER VARCHAR(1),
     ADDRESS VARCHAR(200),
     REFERRED_DOCTOR VARCHAR(50),
     PHONE_NUMBER INT,
     CUSTOMER_EMAIL VARCHAR(100) NOT NULL);

create table TEST_CATEGORY
    (
    TEST_CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
    TEST_CATEGORY_NAME VARCHAR(50) NOT NULL 
    );

create table TEST
    (TEST_ID INT PRIMARY KEY AUTO_INCREMENT,
    TEST_CATEGORY_ID INT NOT NULL,
    TEST_NAME VARCHAR(50) NOT NULL,
    NORMAL_RANGE VARCHAR(50) NOT NULL,
    FOREIGN KEY (TEST_CATEGORY_ID) references TEST_CATEGORY(TEST_CATEGORY_ID));


create table TEST_RECORD
     (PATIENT_ID INT NOT NULL ,
     TEST_ID INT NOT NULL ,
     DATE_TIME DATE NOT NULL ,
     REPORT_ID INT NOT NULL, 
     OBSERVED_VALUE VARCHAR(50),
     PRIMARY KEY (PATIENT_ID, TEST_ID, DATE_TIME),
     FOREIGN KEY(TEST_ID) references TEST (TEST_ID),
     FOREIGN KEY(PATIENT_ID) references PATIENT(PATIENT_ID)
     );






-- create table REPORT_TABLE 
--     (
--      REPORT_ID INT PRIMARY KEY AUTO_INCREMENT,
--      TEST_ID INT,
--      DAT_TIME DATE NOT NULL,
--      PATIENT_ID INT NOT NULL,
--      FOREIGN KEY (PATIENT_ID) references TEST_RECORD (PATIENT_ID), FOREIGN KEY(TEST_ID) references TEST_RECORD(TEST_ID));

create table  USER 
    (
        ID INT UNIQUE NOT NULL ,
        USER_TYPE VARCHAR(10) NOT NULL,
        USER_NAME VARCHAR(50) NOT NULL UNIQUE,
        PASSWORD VARCHAR(50) NOT NULL,
        EMAIL VARCHAR(50) NOT NULL UNIQUE,
        PHONE_NUMBER INT NOT NULL UNIQUE);


INSERT INTO patient (`PATIENT_ID`, `FIRST_NAME`, `LAST_NAME`, `AGE`, `GENDER`, `ADDRESS`, `REFERRED_DOCTOR`, `PHONE_NUMBER`, `CUSTOMER_EMAIL`) VALUES (NULL, 'SURAG', 'YS', '24', 'MALE', 'SCU', 'YUXI', '1234123412', 'surag@gmail.com');
INSERT INTO `lab`.`patient` (`PATIENT_ID`, `FIRST_NAME`, `LAST_NAME`, `AGE`, `GENDER`, `ADDRESS`, `REFERRED_DOCTOR`, `PHONE_NUMBER`, `CUSTOMER_EMAIL`) VALUES (NULL, 'Ramya', 'V', '99', 'F', 'SCU', 'Divya', '147483647', 'ramya@gmail.com');
INSERT INTO `lab`.`test_category` (`TEST_CATEGORY_ID`, `TEST_CATEGORY_NAME`) VALUES ('1', 'DC');
INSERT INTO `lab`.`test_category` (`TEST_CATEGORY_ID`, `TEST_CATEGORY_NAME`) VALUES ('2', 'DIABETES');
INSERT INTO `lab`.`test` (`TEST_ID`, `TEST_CATEGORY_ID`, `TEST_NAME`, `NORMAL_RANGE`) VALUES (NULL, '1', 'Haemoglobin', '13.5-18g/dl'); 


INSERT INTO `lab`.`test` (`TEST_ID`, `TEST_CATEGORY_ID`, `TEST_NAME`, `NORMAL_RANGE`) VALUES ('1', '1', 'Haemoglobin', '13.5-18g/dl');
INSERT INTO `lab`.`test` (`TEST_ID`, `TEST_CATEGORY_ID`, `TEST_NAME`, `NORMAL_RANGE`) VALUES ('3', '1', 'TC(Total Count)', '4000-1100 cells/cumm');
INSERT INTO `lab`.`test` (`TEST_ID`, `TEST_CATEGORY_ID`, `TEST_NAME`, `NORMAL_RANGE`) VALUES ('4', '2', 'RBC', '3.7-5.6 millions/cumm');
INSERT INTO `lab`.`test` (`TEST_ID`, `TEST_CATEGORY_ID`, `TEST_NAME`, `NORMAL_RANGE`) VALUES ('5', '1', 'PCV', '38-52%');


INSERT INTO `lab`.`test_record` (`PATIENT_ID`, `TEST_ID`, `DATE_TIME`, `REPORT_ID`, `OBSERVED_VALUE`) VALUES ('1', '3', '2016-03-10', '1', '12');



